---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-app-ooo-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/slallemand/my-quarkus-app-ooo-gitops.git